### ISSUE TITLE
aria2c功能的建议

### ISSUE THREAD

**Issue by wnbh** [liupan1890/xiaobaiyang#10]
已测试，成功调用aria2c下载，如果可能，希望后续跟进对https的支持，我用大佬仓库搭建的离线下载至网盘是https，我不懂怎样把它改为http

**Comment by liupan1890** [comment]
是我刚开始测试的时候，备注写错了，支持http,https 不支持ws,wss

**Comment by liupan1890** [comment]
所以你不需要改

**Comment by wnbh** [comment]
我试过了，https不行，可能是我那个PRC协议是wss，但是我在AriaNg上把协议改成https也能连接上，浏览器插件aria推送地址我写的https，也能推送成功，咋回事？

**Comment by liupan1890** [comment]
看到你的留言，我专门去测试了一下(下面是具体步骤，注意ip，域名是举例，我测试时是使用真实数据)

1 创建一台Ubuntu 18,ip=1.1.1.1
2 创建一个域名aria.baidu.com,解析到1.1.1.1
3 在Ubuntu 18配置好静态网站
4 申请该域名的Let's Encrypt免费证书并设置网站

===========截止到这里，已经可以正常访问网站https://aria.baidu.com/======

5 保存证书(/root/aria.pem,/root/aria.key)
6 使用一键脚本安装aria（doubi）
7 更改/root/.aria2/aria2.conf,开启ssl和配置证书路径，重启aria
8 打开aria2.net,修改ariaNg的设置
Aria2 RPC 地址   https://aria.baidu.com:6800/jsonrpc
Aria2 RPC 协议   https
Aria2 RPC Http 请求方法 POST
Aria2 RPC 密钥   ****************
刷新页面

===========截止到这里，已经可以正常使用ariaNg=====================

9 修改6盘小白羊Aria.exe同目录的aria2.config
Server=https://aria.baidu.com:6800/jsonrpc
Token=****************

===========截止到这里，已经可以正常使用6盘小白羊版离线aria==============


如上

我测试了，https没有问题，是正常的，aria的功能（添加任务，下载，暂停，删除）都是正常的，跟直接使用ariaNg一致

你为什么不行？应该是你具体的设置的问题，这个我无法帮你解决了。

备注一下：aria2.net可能会自动启动已暂停的任务，如果你开着小白羊，你暂停一个任务，此时打开aria2.net，任务可能会自动启动继续下载（小白羊还显示为暂停中），会造成显示混乱，这个不是我的锅

**Comment by wnbh** [comment]
我用大佬的仓库在heroku上搭建的 估计还是得支持wss才能调用 不懂怎么修改大佬的仓库来改变PRC协议

**Comment by wnbh** [comment]
可能支持wss协议之后，在小白杨里写https也能推送成功，谷歌浏览器里的插件，推送地址只能写http或者https，但或许它本身也支持ws或者wss，只是需要用http和https替换

**Comment by liupan1890** [comment]
我感觉你就是没搞懂，你到底开没开https。

================================================

如果你使用Server=http://aria.baidu.com:6800/jsonrpc  可以访问
使用      Server=https://aria.baidu.com:6800/jsonrpc 不可以访问

那说明你没有开启https！！！你只开了http+ws，你没开启https+wss

================================================

你说你是wss，

那说明你开启了https+wss
开启wss的前提是开启https，它俩是一起开关的。不能单独开wss不开https。不能！！！

================================================

针对https（wss）
只能用域名形式  Server=https://aria.baidu.com:6800/jsonrpc
不能用IP形式    Server=https://1.1.1.1:6800/jsonrpc
因为https的前提是域名+证书，不能用IP。
所以如果你填写的是https://1.1.1.1:6800/jsonrpc这个样子，说明你没有开启https功能！！！

================================================

只要ariaNG可以使用，那小白羊就可以使用，跟你说的wss无关！！！！不能使用的唯一可能就是你填写地址填写的不正确！！！

Server=https://aria.baidu.com:6800/jsonrpc  这里你填的不正确！！！如果你没开启https，那就必须填http://aria.baidu.com:6800/jsonrpc

================================================

你最开始说：“已测试，成功调用aria2c下载，如果可能，希望后续跟进对https的支持”

你怎么测试的？填写heroku的地址（http的）测试成功？那说明你没开启https！！！！！

你没开https，就不能填https的地址

**Comment by liupan1890** [comment]
我用大佬的仓库在heroku上搭建的   

你把仓库地址告诉我，我去看看，我没见过默认开启https的仓库，

因为一般的仓库都是帮你配置好aria，然后你自己绑定域名上传证书文件修改aria2.conf文件开启https

因为每个人的域名和证书都是独一无二的，任何仓库也没办法帮你设置证书，只能你自己手动设置证书

可能是我没遇到过，你发我仓库地址我去试试

**Comment by liupan1890** [comment]
或者你把你的aria rpc 调用地址告诉我，不要告诉我密码，我直接就能测试你是否开启了https

像这样的 https://aria.baidu.com:6800/jsonrpc

**Comment by wnbh** [comment]
> 我用大佬的仓库在heroku上建造的
> 
> 你把仓库地址告诉我，我去看看，我没见过默认开启https的仓库，
> 
> 因为一般的仓库都是帮你配置好aria，然后你自己的绑定域名上传证书文件修改aria2.conf文件开启https
> 
> 因为每个人的域名和证书都是独一无二的，任何仓库也没办法帮你设置证书，只能你自己手动设置证书
> 
> 可能是我没遇到过，你发我仓库地址我去试试

maple3142 / heroku-aria2c

**Comment by wnbh** [comment]
> 或者你把你的aria rpc调用地址告诉我，不要告诉我密码，我直接就能测试你是否开启了https
> 
> 像这样的https://aria.baidu.com:6800/jsonrpc

https://gd-aria2c.herokuapp.com:443/jsonrpc

**Comment by wnbh** [comment]
AriaNg上用http或者ws连接不成功，用https或者wss能连上，应该是开启了https和wss
我在小白杨上应该填https://gd-aria2c.herokuapp.com:443/jsonrpc
我确实是这样填的，就没推送成功

**Comment by liupan1890** [comment]
该怎么解释呢..............

心思很乱啊。。。。。。。。

先说结果：OK啦

1 我的账号，你可以测试测试，一切正常

Server=https://taria.herokuapp.com:443/jsonrpc
Token=44b11bd2ba34dbebcdb1


2 分析
1 https://github.com/maple3142/heroku-aria2c 并没有开启https，是http
2 herokuapp.com 自己强制开启https，自己内部做了转发（https-->http）

所以你是对的，你只能用https+wss


3 检查BUG

没查到，我直接用heroku-aria2c 在heroku上 CreatApp啊，什么设置也没修改
最后我分析到一点，你的密码或许每天对，也可能是你的密码太短。因为我在小白羊限制的是，密码最短要11位。少于11位的密码（Token=）我会直接抛弃。你看你的密码是不是比较短？或者用我的账号试试（最上面的）


补充说明：heroku在us，所以国内访问速度很慢，部分地区甚至无法正常访问，导致小白羊刷新的会很卡，，是因为网络延时太高了

**Comment by wnbh** [comment]
嗯，确实是密码短了点，现在可以了，还有一点，就是推送任务的线程有点少，推送的任务能不能不对线程限制，线程由aria2c配置文件决定
