### ISSUE TITLE
分享的百度链接用aria2不能下载 有啥办法能解决吗

### ISSUE THREAD

**Issue by jzysl123** [liupan1890/xiaobaiyang#11]
有啥办法能把6盘vip账号百度离线完的文件的6盘下载地址共享出来 调用到aria2中吗

**Comment by liupan1890** [comment]
抱歉，这个不能，

现在的逻辑是：

你打开6pan.cn,登录你自己的6pan账号，添加百度链接的离线任务，等离线成功。

打开小白羊，打开你的6盘文件列表，找到刚刚离线成功的文件，下载---aria选中

**Comment by liupan1890** [comment]
电驴，磁力都可以直接在小白羊中添加离线任务+aria，

就是百度链接麻烦，不可以直接在小白羊中添加离线任务+aria

**Comment by liupan1890** [comment]
嗯 是的，6盘只对VIP开放百度
