### ISSUE TITLE
推送到vps的Aria2c 线程数只有4 而且下载文件夹是一个一个推送

### ISSUE THREAD

**Issue by jzysl123** [liupan1890/xiaobaiyang#12]
下载完后vps里的已完成记录就被删掉了，能不能保存
同时下载文件数能不能调大一点 比如5  线程好像并没太大影响

**Comment by liupan1890** [comment]
1 线程数

6盘本身对连接数限制很严格（官方说3文件*单文件5线程，实际上是按照QPS去限制的，根本不是15同时连接数限制）。

我测试的结果，5连接数，4MB分片，下载一个3GB的文件，下载到2.5GB这样就突然失败---没有速度--返回502错误。必须要等1分钟-5分钟才能继续下载。就是被限制了

我也测试了，连接数对下载速度影响不大，我4链接，下载速度在80MB/s这样，我10链接，下载速度还是80多，并没有增加

我还测试了，部分文件从6盘下载很慢，4链接或者10链接，都很慢，都小于2MB/s，跟文件有关

总之你要多的连接数没用，速度并不会明显提升，反而会导致几率被502

可能你知道突然下载失败是因为连接数太多被502了，大部分用户并不明白，他们只知道小白羊经常下载失败。为了减少下载失败，我限制的4链接，在设置页面，没有地方放一个修改连接数的选项

2 下载结果我自动删除是因为下载结果多了，aria容易崩溃。

不知道你想保留下载结果的目的是什么呢？

**Comment by liupan1890** [comment]
### 问题1 线程数只有4

6盘本身对连接数限制很严格（官方说3文件*单文件5线程，实际上是按照QPS去限制的，根本不是15同时连接数限制）。

我测试的结果，5连接数，4MB分片，下载一个3GB的文件，下载到2.5GB这样就突然失败---没有速度--返回502错误。必须要等1分钟-5分钟才能继续下载。就是被限制了

我也测试了，连接数对下载速度影响不大，我4链接，下载速度在80MB/s这样，我10链接，下载速度还是80多，并没有增加

我还测试了，部分文件从6盘下载很慢，4链接或者10链接，都很慢，都小于2MB/s，跟文件有关

总之你要多的连接数没用，速度并不会明显提升，反而会导致几率被502

可能你知道突然下载失败是因为连接数太多被502了，大部分用户并不明白，他们只知道小白羊经常下载失败。为了减少下载失败，我限制的4链接，在设置页面，没有地方放一个修改连接数的选项


### 问题2 同时下载文件数能不能调大一点

同上，同时下载多个文件，也容易导致502。最稳定的，就是只下载一个文件+线程数4+分片体积大于10MB

### 问题3 下载文件夹是一个一个推送

同上，一起推送会导致多个文件同时下载

### 问题4 下载完后vps里的已完成记录就被删掉了

下载结果我自动删除是因为下载结果多了，aria容易崩溃。

不知道你想保留下载结果的目的是什么呢？

**Comment by wnbh** [comment]
我觉得可以对线程数不做限制或者把线程提高一点，同时下载多少个文件可以自己设置，但最多不超过5个的样子，大佬你可以在aria2c推送下载申明一下，多线程多任务容易造成下载失败，502。当然，最终怎样还是大佬你来决定，我们提意见

**Comment by jzysl123** [comment]
本地原来有个已完成 那就没必要留着记录了

**Comment by liupan1890** [comment]
在下一个正式版本发布时，会支持在aria.config文件配置Server=下面继续配置SplitSize个ConnNum的
