### ISSUE TITLE
可以增加在线播放视频吗

### ISSUE THREAD

**Issue by Minscs** [liupan1890/xiaobaiyang#14]
这个应该不难吧，把链接提取出来调用下播放器就行了

**Comment by liupan1890** [comment]
嗯，很抱歉不行

6盘限制只有VIP用户才可以预览

所以具体的操作是：
1解析出你要播放的文件的hash值，
2利用秒传接口把这个文件复制到我的6盘账号里（VIP）
3调用预览api解析出最终的播放地址
4小白羊调用你电脑上支持m3u8的播放器播放

遇到的问题是
1我的账号只有6T空间，当预览的人比较多时，空间不够用，所以需要我有很多VIP账号
2我无法知道你的电脑上有什么播放器、浏览器，所以需要你手动配置(每一种播放软件的配置都是独特的)或者安装包直接附带一个播放器（50MB），这2种方案都不优雅

所以我不会添加预览功能，因为没有优雅的解决方案。你下载后再播放比我增加预览更简单

**Comment by Minscs** [comment]
把链接提取后用调用PotPlayer或者系统默认播放器也可以啊
![1](https://user-images.githubusercontent.com/68373675/89270487-fba69880-d66d-11ea-9853-83f1453022e4.png)
![2](https://user-images.githubusercontent.com/68373675/89270493-fd705c00-d66d-11ea-841e-22e3825533ef.png)
![3](https://user-images.githubusercontent.com/68373675/89270498-ff3a1f80-d66d-11ea-8246-26cb29bdf861.png)

**Comment by liupan1890** [comment]
对哦，是我没想到，你太聪明了。。。。。。

我现在实际上是在学习golang，再用go开发一遍新的版本，实现win+linux都可以用。。。。。

所以小白羊我没时间更新了。。。。。。。

我会在新版本里添加此功能
