### ISSUE TITLE
这个客户端默认应该是多线程下载吧，官方的客户端可以设置。

### ISSUE THREAD

**Issue by Columba2017** [liupan1890/xiaobaiyang#15]

**Comment by liupan1890** [comment]
1 可以多线程，6盘官方支持多线程

2 你的意思是想多个文件同时下载对吧？
我实际测试发现，多文件同时下载，当你网速比较快时（10MB/s）,会频繁的触发6盘官方的限速（返回502）导致下载失败

所以我直接设置为单文件下载（5线程分片并发下载），不会支持多文件同时下载的，因为容易导致下载失败啊
