### ISSUE TITLE
希望支持多任务下载啦

### ISSUE THREAD

**Issue by Huansheng1** [liupan1890/xiaobaiyang#17]
偶尔链接解析有点问题，链接没问题说404

**Comment by liupan1890** [comment]
我实际测试发现，多文件同时下载，当你网速比较快时（10MB/s）,会频繁的触发6盘官方的限速（返回502）导致下载失败

所以我直接设置为单文件下载（5线程分片并发下载），不会支持多文件同时下载的，因为容易导致下载失败啊

**Comment by liupan1890** [comment]
链接没问题说404  应该是当时提交任务的人比较多导致

**Comment by Huansheng1** [comment]
哦哦，磁力链接和度盘全是从6盘拉取的啊，我希望加上个多线程下载开关，是因为下载多个小文件时能避免每次链接新资源较长导致的平均速度在几百K（默认关闭，别人开启时提示别人网速大于十M时不建议开启）
不过，404的原因我明白了，是因为自动从剪辑板读取云盘链接时会少掉最后一个符号，你可以试一下

**Comment by liupan1890** [comment]
我去测试一下

**Comment by Huansheng1** [comment]
> 我去测试一下

部分链接会这样（自动识别缺少最后一个字符），现在我又没碰见了，可能链接问题吧（等我碰见了再发你给看看哈），我也不知道为啥；
另外，部分链接能能解析，但不会显示文件， 比如这个链接: https://pan.baidu.com/s/1tv7CV0k0-umhcX7-EY3GwQ 提取码: 2333（一会取消）

最后呢，我再提个小建议啊，希望设置加入失败自动重连开关（比如重连三次），有些文件第一次下着下着就失败，重新连接下就没问题了

**Comment by liupan1890** [comment]
1 再自动复制粘贴 无密码的  分享链接 时，会漏掉链接的最后一位，导致404

2 比如这个链接: https://pan.baidu.com/s/1tv7CV0k0-umhcX7-EY3GwQ 是因为文件夹太多

**Comment by Huansheng1** [comment]
> 1 再自动复制粘贴 无密码的 分享链接 时，会漏掉链接的最后一位，导致404
> 
> 2 比如这个链接: https://pan.baidu.com/s/1tv7CV0k0-umhcX7-EY3GwQ 是因为文件夹太多

哦哦，好的
