### ISSUE TITLE
SHA校验失败

### ISSUE THREAD

**Issue by mekozoko** [liupan1890/xiaobaiyang#18]
开启校验后，同一个文件下了5次都说校验失败，根本无法成功……所以这个功能是鸡肋吗

**Comment by liupan1890** [comment]
嗯，我本地测试的时候，是正常的，有时候就是会下载失败，下载的文件是损坏的，这个时候校验功能能发觉文件损坏

但是文件损坏是极偶尔才会遇到的，所以默认是关闭校验功能的

你提到连续5次都失败，可能是节点缓存错误，也可能是校验功能本身有BUG。

这个我还没测试出来

**Comment by liupan1890** [comment]
我连续测试了800多个文件（磁力，分享链接，大文件，小文件，各种格式的文件），都无法遇到校验失败，，，，我还是没能找出来问题在哪
