### ISSUE TITLE
关于账号登陆

### ISSUE THREAD

**Issue by miuicat** [liupan1890/xiaobaiyang#2]
大大啥时候把登陆做上去啊，顺带把文件上传也做上去哦，谢谢

**Comment by liupan1890** [comment]
嗯，这是个不开源的项目。登录功能会涉及到你的账号和密码，属于用户隐私，为了避免此类问题，我没有做登录功能。就是简单的直接下载多方便。


文件上传依赖登录功能，因为不需要登录，所以也不能上传。

最关键的是，我自己只用到了离线下载功能，我并不使用6pan存储文件。所以一开始就没考虑到要加登录和上传。so 很抱歉不会有的
