### ISSUE TITLE
请问文件下载后，除了文件还有什么留在电脑上的附带文件嘛？

### ISSUE THREAD

**Issue by 1198560751** [liupan1890/xiaobaiyang#20]

**Comment by liupan1890** [comment]
第一部分：会在你指定的下载目录下创建的文件

比如你下载的是《你的名字.mp4》
那么，下载中，会创建《你的名字.mp4.6pan》临时文件，下载结束会重命名为《你的名字.mp4》

比如你下载的文件包含路径（下载文件夹、多级嵌套的文件夹）

那么会完整的按照6盘根目录/你下载的文件夹/二级文件夹/你的名字.mp4 去创建所有的文件夹，包括空的文件夹

第二部分：会在6盘小白羊版.exe程序启动目录创建的文件

会在/data/文件夹下创建datav1.db，LiuPan.log，LocalStorage/https_account.6pan.cn.localstorage

除此之外，并不会创建任何其他文件，只涉及《下载目录》《程序启动目录》

**Comment by liupan1890** [comment]
为什么要问这个呢？

**Comment by 1198560751** [comment]
哦哦，谢谢回复。就是问一下下载后会有没有附带文件，可以删除以免占用内存

**Comment by 1198560751** [comment]
> 为什么要问这个呢？

哦哦，谢谢回复。就是问一下下载后会有没有附带文件，可以删除以免占用内存
