### ISSUE TITLE
开发者能不能做个磁盘映射啊，就跟onedrive或者Gdrive那样的可以自动同步的

### ISSUE THREAD

**Issue by Frankklk** [liupan1890/xiaobaiyang#21]

**Comment by liupan1890** [comment]
1 磁盘映射这个功能应该是指webdav
2 6盘官方https://www.cnblogs.com/6pan/p/13424242.html说近期会开放
等官方开放webdav功能，你直接配置一下就可以用了，并不需要我开发

3 自动同步
自动同步功能跟磁盘映射功能完全没关系，是2个不同的概念，好比手机和电视，完全没关系（虽然都能看电影）
自动同步是一个单独的功能，磁盘映射是一个单独的功能。不要混为一谈。

假如你是想实现同步盘的功能，这个我不会做，涉及到文件版本控制，不同电脑上产生的同名新旧文件，应该保留哪个删除哪个？一不小心就会崩，我不会做这种危险的功能。6盘官方也没有支持同步盘功能

**Comment by liupan1890** [comment]
如果你是想要aria下载后自动上传到google drive或one drive 请参阅调用Aria2c下载.md

**Comment by Frankklk** [comment]
感谢开发者的热心回复
