### ISSUE TITLE
为什么下载不停掉线

### ISSUE THREAD

**Issue by kitkw** [liupan1890/xiaobaiyang#22]
每隔一段时间就会掉线，要重链

**Comment by liupan1890** [comment]
6盘给下载链接限制约为30分钟失效，网速慢+大文件就会下载失败，点击下载按钮重新下载就好了，会自动断点续传

**Comment by kitkw** [comment]
原来这样！！在下载一个67G的大文件 不停断开。30分钟的时间也太短了...........

**Comment by kitkw** [comment]
> 6盘给下载链接限制大约30分钟失效，网速慢+大文件就会下载失败，点击下载按钮重新下载就好了，会自动断点续传

好像没有30分钟就断开了。10分钟左右就不行了  虽然能续传

**Comment by liupan1890** [comment]
超时的时间，是6盘控制的，我只是读取到下载链接，但读取到的链接本身已经被设置好超时时间了。所以具体几分钟超时，是看6盘的设置
