### ISSUE TITLE
作为一个第3方网盘客户端，希望能达到pandownload那样的效果

### ISSUE THREAD

**Issue by QRQF001** [liupan1890/xiaobaiyang#23]
可以参考pandownload的**UI**，6盘账号放在顶部，下面是刷新，返回，首页，离线，
文件名左侧有复选框，或者**按Ctrl，shift，可以多选**，
可自定义 **背景图片 及 主题颜色**

**Comment by liupan1890** [comment]
抱歉啊，这个项目只是方便我自己使用的，功能已经满足我个人需求了，我也没有经历去维护此项目，已经停止更新了
