### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by winlock** [liupan1890/xiaobaiyang#26]
1.不能识别手机版的百度盘链接，如：https://pan.baidu.com/wap/init?surl=a3kVUu4x_TA1Yk4uwHWYvQ
2.新建任务经常把list当作提取码，其实不过因为复制的链接是这样：https://pan.baidu.com/s/1MInxqA-X3esC-mw5eqC5YQ#list/path=%2F

**Comment by liupan1890** [comment]
感谢你的反馈，

wap确实不能识别，之前没遇到过（我都是电脑端）
list的问题也存在

其实都是简单的替换一下字符串就好了，但是需要修改代码并发布新版本，让所有人都升级后才能修复此问题

我会咋下个版本修正这些问题
