### ISSUE TITLE
软件自动读取剪贴板时少最后一个字符

### ISSUE THREAD

**Issue by ps4jpacce** [liupan1890/xiaobaiyang#31]
![Q3Q0BN8FFYRHB0Z64M2KU00](https://user-images.githubusercontent.com/56801153/92071757-29543e00-ede2-11ea-8e29-2887e22e4e23.png)

**Comment by liupan1890** [comment]
感谢反馈，确实是，当仅复制了分享链接（没有复制提取码时），自动粘贴功能会漏掉最后一位，导致最后显示404错误

**Comment by ps4jpacce** [comment]
Thank you for reply.
