### ISSUE TITLE
账号登录问题

### ISSUE THREAD

**Issue by QRQF001** [liupan1890/xiaobaiyang#32]
6盘小白羊，只能同时登录6个账号，不能再增加登录账号
因为是6盘，空间有6T，所以作者是故意设置只能同时登录6个账号？还是因为没想到有人会无聊到这个地步
（其实是我买了10来个6盘非会员账号，每天用这个每天离线一点文件，网页版切换比较麻烦，这个挺好用的）

**Comment by liupan1890** [comment]
感谢反馈

1 从程序设计上没有限制账号数量

2 有一个已知的BUG，点击账号列表时，下拉可以显示不限量的账号，但点击账号名（切换到此账号）时因为BUG只能选择前5个账号

是程序BUG导致的只能登录5个账号

**Comment by liupan1890** [comment]
临时的解决办法是，
1 你创建一个文件夹比如叫《小白羊1》，在里面复制一份6盘小白羊版.exe,运行这个程序登录5个账号

2  你创建一个文件夹比如叫《小白羊2》，在里面复制一份6盘小白羊版.exe,运行这个程序登录另外5个账号

以此类推

原理是：6盘小白羊版.exe会把登陆的账号信息保存到程序文件/data/datav1.db

就是说6盘小白羊版.exe是完全独立的程序，所有数据都保存在程序文件/data/里面，不会污染系统目录，所以可以通过复制多个文件夹副本实现突破多用户登录BUG

**Comment by liupan1890** [comment]
特别留意一下，6盘小白羊版.exe并不能多开（同时运行多个），所以一定要先退出《小白羊1》，再执行《小白羊2》。否则你会说怎么不管用？因为你一直在运行《小白羊1》

**Comment by QRQF001** [comment]
懂了，和PD多开一样的，只能同时运行一个
