### ISSUE TITLE
咋就暂停下载了

### ISSUE THREAD

**Issue by zfk513** [liupan1890/xiaobaiyang#33]
百度真的🐕
我这IP怕是限速了
IDM也跑不起来了
直接403不给下 试了好多次

**Comment by QRQF001** [comment]
使用的文叔叔网盘，文件过了有效期，链接失效了
作者拿自己的6盘VIP账号给别人离线文件，功能类似于共享账号
如果你是做网盘的，应该不想这样的事情发生吧
当然，也可能是白嫖党过多

**Comment by liupan1890** [comment]
你可以 百度一下下载啊
