### ISSUE TITLE
 怎样使用自己的vip账号下载百度分享链接啊？

### ISSUE THREAD

**Issue by yagay** [liupan1890/xiaobaiyang#34]
想问下怎么样使用自己的vip账号下载百度分享链接？默认是用的内置账号，有次数限制，我登录了我自己的账号还是不能调用自己的账号下载百度分享链接，，有没有办法解决下？官方客户端默认是要离线成功才能下载，没有你这个客户端方便，，希望解决下，，谢谢

**Comment by QRQF001** [comment]
作者做的这个客户端，默认是用他的账号进行离线，软件暂时无法解决你的问题
建议作者增加一个功能
离线文件时，【默认】选择作者的内置账号，当然也可以将【默认选项】修改成自己的账号

**Comment by liupan1890** [comment]
在软件发布时，大家基本上都是6盘免费用户（6盘更开始收费，免费也不限速）

所以如果不使用内置账号，是不可以添加分享链接的。
所以就干脆直接判断是分享链接就调用内置账号

没有考虑到让用户自主选择


后来我一直没更新，，别问，问就是拖延症犯了

**Comment by CRO2017** [comment]
大佬,小白羊百度云离线次数用光啦,可以更新吗 :(

**Comment by ANM-WYX** [comment]
大佬能不能在搜索页面显示 搜索出来的分享的链接啊，现在的搜索只能用内置的离线，可是每次都用完，我自己买了vip都无能为力

**Comment by CRO2017** [comment]
> 大佬能不能在调用的小白杨搜索页面显示搜索出来的分享的链接啊，现在的搜索只能用内置的离线下载，可是最近每次都显示都用完，我自己买了vip都无能为力（也无法查看分享链接）。

百度网盘资源搜索可以使用网站引擎,比如免费的大圣盘之类的,查看分享链接与提取码可以选择关注它的公众号或者去greasyfork找脚本,如果你买了6盘的vip可以在6盘网页端进行百度网盘下载,小白羊的内置账号用光了,我也等着作者解决呢🤡🤡🤡

**Comment by ANM-WYX** [comment]
我打错了 小白🐏调用的是猪猪盘搜的共享，但是现在网页版本的猪猪盘我根本进不去，就很尴尬，但是小白羊的却能搜索出来，要是能显示分享链接也好啊。

**Comment by ANM-WYX** [comment]
> > 大佬能不能在调用的小白杨搜索页面显示搜索出来的分享的链接啊，现在的搜索只能用内置的离线下载，可是最近每次都显示都用完，我自己买了vip都无能为力（也无法查看分享链接）。
> 
> 百度网盘资源搜索可以使用网站引擎,比如免费的大圣盘之类的,查看分享链接与提取码可以选择关注它的公众号或者去greasyfork找脚本,如果你买了6盘的vip可以在6盘网页端进行百度网盘下载,小白羊的内置账号用光了,我也等着作者解决呢🤡🤡🤡

我打错了 小白🐏调用的是猪猪盘搜的共享，但是现在网页版本的猪猪盘我根本进不去，就很尴尬，但是小白羊的却能搜索出来，要是能显示分享链接也好啊。

**Comment by CRO2017** [comment]
> > > 大佬能不能在调用的小白杨搜索页面显示搜索出来的分享的链接啊，现在的搜索只能用内置的离线下载，可是最近每次都显示都用完，我自己买了vip都无能为力（也无法查看分享链接）。
> > 
> > 
> > 百度网盘资源搜索可以使用网站引擎,比如免费的大圣盘之类的,查看分享链接与提取码可以选择关注它的公众号或者去greasyfork找脚本,如果你买了6盘的vip可以在6盘网页端进行百度网盘下载,小白羊的内置账号用光了,我也等着作者解决呢🤡🤡🤡
> 
> 我打错了 小白🐏调用的是猪猪盘搜的共享，但是现在网页版本的猪猪盘我根本进不去，就很尴尬，但是小白羊的却能搜索出来，要是能显示分享链接也好啊。

确实,脚本作者也说猪猪盘打不开,小白羊能打开我是不知道的,一直没用小白羊自带的https://greasyfork.org/en/scripts/412173-%E7%BB%95%E8%BF%87%E9%99%90%E5%88%B6%E6%90%9C%E7%B4%A2%E6%9F%A5%E7%9C%8B%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E8%B5%84%E6%BA%90
