### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by Zhao-Peng-Hui** [liupan1890/xiaobaiyang#38]
![image](https://user-images.githubusercontent.com/71930169/96271987-17c89d80-1000-11eb-9ef6-2f8e75956557.png)
![image](https://user-images.githubusercontent.com/71930169/96272192-5d856600-1000-11eb-8a15-3d4e9aa11064.png)
![image](https://user-images.githubusercontent.com/71930169/96272227-67a76480-1000-11eb-95ba-8271b69487cf.png)

开发者您好  我目前搜索出来的东西不能下载，可以帮我搜索一下分享一下百度云盘的链接呢，非常感谢

**Comment by Zhao-Peng-Hui** [comment]
登录自己的6盘账号也不能离线下载呢，请求帮助十分感谢

**Comment by liupan1890** [comment]
pan.baidu.com/s/1ZvJIuZ4C0vJ4TbVD_HmmoQ  提取码  f62r

pan.baidu.com/s/19Z5kYmW6nGyuUu8FsHPufw  提取码   CJPB

**Comment by liupan1890** [comment]
pan.baidu.com/s/1ZvJIuZ4C0vJ4TbVD_HmmoQ  提取码  f62r

pan.baidu.com/s/19Z5kYmW6nGyuUu8FsHPufw  提取码   CJPB

**Comment by Zhao-Peng-Hui** [comment]
感谢 大佬，可以在2.0版本中让用户能看见百度搜索到的链接不

**Comment by rainbowshine521** [comment]
@liupan1890 开发者大大您好，可否也帮我分享一下百度链接呢？非常感谢
[https://raw.githubusercontent.com/rainbowshine521/image/main/1.png](url)
[https://raw.githubusercontent.com/rainbowshine521/image/main/2.png](url)

[https://raw.githubusercontent.com/rainbowshine521/image/main/3.png](url)
[https://raw.githubusercontent.com/rainbowshine521/image/main/4.png](url)
