### ISSUE TITLE
下载文件总是下载根本目录文件夹

### ISSUE THREAD

**Issue by liveskai** [liupan1890/xiaobaiyang#39]
别创建文件夹

**Comment by liupan1890** [comment]
是为了跟6盘的目录一致，这样你一看就直到是下载的哪一个文件、文件夹了  

比如你6盘里有  

/1.mp4    (4GB)
/封神榜/1.mp4     (1.2GB)

注意2个文件不是同一个文件当你下载时，如果没按照6盘的路径去创建对应的文件夹。你可能会混乱，
另外下载时程序也会混乱====你本地已经有一个1.mp4了，你是想覆盖掉，还是想我重命名1(1).mp4?我重命名了你知道你下载的是/封神榜/1.mp4===1(1).mp4吗？

总之会比较乱，所以直接按照6盘路径去创建文件夹了


说到底这个也无关紧要吧，自己手动复制粘贴一下，移动一下文件就好了。
