### ISSUE TITLE
关于APP的一些请求

### ISSUE THREAD

**Issue by qingzhenyun** [liupan1890/xiaobaiyang#4]
您好，我们是清真云官方团队。很感谢您做了这一个APP。
但是我们有以下几点麻烦您予以考虑。

1、因您的APP并不与官方的账户体系挂钩，介于此，尽管您依然可以使用API，但是您不能使用我们的商标，品牌，以及明示或者暗示与6盘的关系（我们的商标也是从第三方公司授权，并不对此品牌拥有独占权，如果您使用将会有法律风险），我们建议您使用独立的APP名字。

2、根据我们和百度网讯公司的沟通，我们并不能直接通过API下载百度网盘的文件，而是通过人工下载的方式（您也注意到最近排队时间较长，且不允许免费试用），如果您使用我们的接口，可能会被百度网讯公司误认为破解百度的链接，从而给您带来法律上的麻烦。

**Comment by liupan1890** [comment]
您的留言我已收到，确实是我考虑的太简单了，

1 我会立即在github说明里注明和6pan无关，因为软件的特殊性---没有自动升级功能--所以我会在下个版本中也修改掉可能会涉及到6pan版权、商标的地方

2 我会立即着手开发新的版本，打开需要3-4天，就可以上线。如果有其它问题或者整改不到位，请继续留言告知

**Comment by qingzhenyun** [comment]
非常感谢！我们仅是为了防范法律层面上的风险。
________________________________
发件人: liupan1890 <notifications@github.com>
发送时间: 2020年7月10日 10:55
收件人: liupan1890/xiaobaiyang <xiaobaiyang@noreply.github.com>
抄送: qingzhenyun <qingzhenyun@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [liupan1890/xiaobaiyang] 关于APP的一些请求 (#4)


您的留言我已收到，确实是我考虑的太简单了，

1 我会立即在github说明里注明和6pan无关，因为软件的特殊性---没有自动升级功能--所以我会在下个版本中也修改掉可能会涉及到6pan版权、商标的地方

2 我会立即着手开发新的版本，打开需要3-4天，就可以上线。如果有其它问题或者整改不到位，请继续留言告知

―
