### ISSUE TITLE
百度分享链接

### ISSUE THREAD

**Issue by LIFRANCKY** [liupan1890/xiaobaiyang#42]
请问为什么我打不开自己分享的链接？虽然写着离线次数没了但我打开别的百度链接或者开始别离线任务都可以。我也有试自己手动粘贴但奇怪的是它显示没输入提取码，然后我刷新后就回到刚才的问题。

**Comment by liupan1890** [comment]
我感觉是你输入的分享链接格式不标准，百度的标准是

链接: https://pan.baidu.com/s/159EE-_Y_4BZr3xxxxxxxx 提取码: rfcr 复制这段内容后打开百度网盘手机App，操作更方便哦 

 当你粘贴这句话到输入框里，会自动识别出提取码，如图：  
 
![无标题](https://user-images.githubusercontent.com/67817756/97334180-66572100-18b7-11eb-8ca6-e6cd31ea0617.png)


如果没识别出，你也可以手动输入，
上面只输入完整的链接：https://pan.baidu.com/s/159EE-_Y_4BZr3xxxxxxxx
下面只输入4位提取码

这样就不会提示你没有输入提取码了，就算你输错了链接或提取码，也只会提示  你输入的链接有误，或提取码不正确

**Comment by liupan1890** [comment]
如果你是用的第一版的话，就不要纠结了，第一版不能输入百度分享链接了---因为内置账号已经因为某些原因被迫关闭了，第一版不支持使用自己的账号提交百度分享链接，你应该去用第二版

**Comment by LIFRANCKY** [comment]
好的，谢谢！看来得另寻办法了，因为本来是想用免费的内置账号。
