### ISSUE TITLE
能否增加个获取6盘内多个和单个文件下载链接的按钮

### ISSUE THREAD

**Issue by jzysl123** [liupan1890/xiaobaiyang#5]
官方一直没弄出来 一直显示测试

还有是否能把6pan的VIP账号离线的文件下载地址显示出来

**Comment by liupan1890** [comment]
### 单个、多个文件的下载地址的按钮

#### 针对单个文件的下载地址：<br/>

你可以在6盘网页版，点击这个文件的下载按钮，然后会弹框，直接下载或者复制下载地址<br/>
对于小白羊，因为是直接就开始下载了，所以并不需要显示复制下载地址，UI上并没有位置显示复制按钮，逻辑上也容易让人混乱。所以你还是直接用官方网页版复制吧<br/>
<br/>
注意一点：小白羊获取的下载地址和你在网页上复制的下载地址都是调用6pan公开api生成的，完全一样，有时效，一般是20分钟失效<br/>


#### 针对多个文件的下载地址：<br/>
你应该是指6盘网页上的   《生成批量下载地址》  这个功能吧  <br/>
这个功能官方并没有提供，我当然也无法提供<br/>
小白羊可以通过遍历文件夹内全部文件，实现的文件夹下载（是生成一堆的文件下载任务，不是把文件打包成一个zip一次性下载）<br/>


### 把6pan的VIP账号离线的文件下载地址显示出来

你是说把我的VIP账号，离线的分享链接，里面的文件，这些文件的下载地址显示出来是吧？<br/>
你是想获取下载地址然后自己用IDM之类下载是吧<br/>

如果我理解正确，还是上面那样，小白羊直接就下载了，UI上也没有地方放一个复制按钮<br/>

**Comment by jzysl123** [comment]
我是想获取下载地址直接vps上下载 不走本地
所以想看看能不能加这个功能

**Comment by liupan1890** [comment]
我想我get到了，vps是linux吧？

这个我也没办法啦，小白羊只支持win，linux运行不了。你只能通过6盘网页版复制下载地址了。6盘官方也没有linux版

**Comment by liupan1890** [comment]
请参与 调用Aria2c下载.md
