### ISSUE TITLE
使用用户 登录 离线bd的话 还有5G的大小限制吗？

### ISSUE THREAD

**Issue by in-out** [liupan1890/xiaobaiyang#6]
使用自己的账户，订阅用户
离线 5G以上的文件的话
无法勾选 Checkbox

**Comment by liupan1890** [comment]
我查了一下，是程序的BUG，对6盘的VIP用户判断失败，现在是所有的百度链接都走内置账号，所以会遇到登录VIP账号还不能5G的问题

第一：下个版本会修正次问题，VIP账号会离线到自己账号内
第二：我已经调整为10GB限制，所以你现在重新提交BD链接就可以了
