### ISSUE TITLE
我们渴望一个上传功能

### ISSUE THREAD

**Issue by miuicat** [liupan1890/xiaobaiyang#7]
如题：现在账号登陆、管理等都有了，那么我们渴望一个上传文件（文件夹）的功能。。。。

**Comment by liupan1890** [comment]
嗯，现在确实没有实现上传。是因为我没打算做上传功能

其实我做这个是为了下载，我从来不往6盘上传文件。像这种网盘，总感觉没啥保障

这样，等几天我再看看，反映的人数多了我就加上上传
