### ISSUE TITLE
希望加一个远程下载

### ISSUE THREAD

**Issue by wnbh** [liupan1890/xiaobaiyang#8]

**Comment by liupan1890** [comment]
增加远程下载

我增加这个功能很麻烦，我还真认真想了一下，怎么生成ID，怎么在别的电脑绑定ID，怎么互相通信，内网的话还是走我服务器通信靠谱，多个地方账号怎么同步，怎么查看远程的下载进度，需要实现的操作增加任务删除任务，开始暂停等等等等

后来就想明白了，我增加这个功能很麻烦，你直接安装一个AnyDesk远程管理不就完了，这多简单？

**Comment by wnbh** [comment]
> 增加远程下载
> 
> 我增加这个功能很麻烦，我还真认真想了一下，怎么生成ID，怎么在别的电脑绑定ID，怎么互相通信，内网的话还是走我服务器通信靠谱，多个地方账号怎么同步，怎么查看远程的下载进度，需要实现的操作增加任务删除任务，开始暂停等等等等
> 
> 后来就想明白了，我增加这个功能很麻烦，你直接安装一个AnyDesk远程管理不就完了，这多简单？

我的意思是添加一个aria2c远程下载，只需要发送到aria2c上就行了，其余的在aria2c上操作就好了，利用aria2c离线下载6盘文件至onedrive，googledrive或者其他在线网盘

**Comment by liupan1890** [comment]
get了，抱歉之前确实没理解到

我研究一下，看下个版本能否加上，理论上是可以的，就是得去扣代码了，，，，，没开发过aria项目，需要多点时间

**Comment by wnbh** [comment]
> get了，抱歉之前确实没理解到
> 
> 我研究一下，看下个版本能否加上，理论上是可以的，就是得去扣代码了，，，，，没开发过aria项目，需要多点时间

多点时间没关系，这个功能加上了就很厉害了。

**Comment by liupan1890** [comment]
请参与 调用Aria2c下载.md

**Comment by wnbh** [comment]
好的
